-- Blocked-word check for names other players can see (account display name and
-- mascot name). The check lives in the database so it cannot be bypassed by
-- calling the API directly; the client runs the same vocabulary first to give
-- a clear message (lib/domain/name-filter.ts).
--
-- Deliberately NOT a CHECK constraint: the vocabulary will change over time and
-- a constraint would then block unrelated updates of rows that were valid when
-- written (for example feeding the mascot updates maso_status).
--
-- Rejection is reported as errcode 22023 with the message 'name not allowed' so
-- the client can tell it apart from ordinary input errors.

-- Generated by scripts/generate-name-filter-sql.mjs from lib/domain/name-filter-terms.json.
-- Same normalization as toSkeleton() in lib/domain/name-filter.ts:
-- NFKC, lower case, katakana to hiragana, digit look-alikes, then keep only
-- ASCII letters/digits, hiragana, the long vowel mark and kanji.
create or replace function public.name_skeleton(p_name text)
returns text
language sql
immutable
set search_path = ''
as $$
  select regexp_replace(
    translate(
      translate(
        lower(normalize(coalesce(p_name, ''), NFKC)),
        'ァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヰヱヲンヴヵヶ',
        'ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわゐゑをんゔゕゖ'
      ),
      '01345@$',
      'oieasas'
    ),
    '[^a-z0-9\u3041-\u3096\u30fc\u3400-\u4dbf\u4e00-\u9fff]',
    '',
    'g'
  )
$$;

-- False when the name contains a blocked term. "contains" terms are matched in
-- the skeleton; "tokens" only as whole ASCII words.
create or replace function public.is_name_allowed(p_name text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    not exists (
      select 1
      from unnest(
        array['死ね', '殺す', '殺せ', 'ぶっ殺', 'ころすぞ', '自殺', 'fuck', 'shit', 'bitch', 'bastard', 'asshole', 'motherfucker', 'dickhead', 'whore', 'slut', 'ちんこ', 'ちんぽ', 'まんこ', 'せっくす', 'おなにー', 'ふぇらちお', '中出し', '強姦', 'れいぷ', 'ぽるの', 'やりまん', 'porn', 'penis', 'vagina', 'pussy', 'rapist', 'きちがい', '気違い', '池沼', 'かたわ', 'nigger', 'nigga', 'faggot', 'cunt', 'nazi', 'hitler', '運営', '管理人', '管理者', '事務局', '公式', '開発者', 'administrator', 'moderator']::text[]
      ) as blocked(term)
      where position(blocked.term in public.name_skeleton(p_name)) > 0
    )
    and not exists (
      select 1
      from regexp_split_to_table(
        translate(lower(normalize(coalesce(p_name, ''), NFKC)), '01345@$', 'oieasas'),
        '[^a-z0-9]+'
      ) as word(value)
      where word.value = any (
        array['ass', 'dick', 'cock', 'tits', 'sex', 'rape', 'anal', 'nsfw', 'xxx', 'porno', 'kkk', 'fag', 'admin', 'official', 'staff', 'support', 'system', 'owner', 'mod', 'root']::text[]
      )
    )
$$;

-- Names saved before the filter existed and that the filter now rejects are
-- reset to the defaults (no one is shown a blocked name).
update public.profiles
set display_name = 'トレーニー'
where not public.is_name_allowed(display_name);

update public.maso_status
set maso_name = 'マソ君'
where not public.is_name_allowed(maso_name);

create or replace function public.initialize_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_display_name text;
begin
  -- An unusable or blocked name falls back to the default instead of making
  -- the sign-up fail with a database error.
  v_display_name := public.clean_display_name(
    new.raw_user_meta_data ->> 'display_name',
    'トレーニー'
  );
  if not public.is_name_allowed(v_display_name) then
    v_display_name := 'トレーニー';
  end if;

  insert into public.profiles (id, display_name)
  values (new.id, v_display_name)
  on conflict (id) do nothing;

  insert into public.user_settings (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.maso_status (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.foods (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.exercises (
    user_id, name, body_part, is_default,
    master_key, calculation_pattern, bw_ratio, is_isometric
  )
  select new.id, m.name, m.body_part, true,
    m.master_key, m.calculation_pattern, m.bw_ratio, m.is_isometric
  from public.exercise_master() as m
  on conflict do nothing;

  return new;
end;
$$;

revoke all on function public.initialize_new_user() from public, anon, authenticated;

create or replace function public.rename_maso(
  p_name text,
  p_expected_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_name text;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;

  if p_expected_user_id is null or p_expected_user_id <> v_user_id then
    raise exception 'authentication context changed' using errcode = '42501';
  end if;

  if p_name is null or char_length(p_name) > 200 then
    raise exception 'invalid name' using errcode = '22023';
  end if;

  v_name := public.normalize_display_name(p_name);
  if char_length(v_name) not between 1 and 30 then
    raise exception 'invalid name' using errcode = '22023';
  end if;

  if not public.is_name_allowed(v_name) then
    raise exception 'name not allowed' using errcode = '22023';
  end if;

  update public.maso_status
  set maso_name = v_name
  where user_id = v_user_id;

  if not found then
    raise exception 'maso status missing' using errcode = 'P0002';
  end if;

  return jsonb_build_object('name', v_name);
end;
$$;

create or replace function public.update_display_name(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_name text;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;

  if p_name is null or char_length(p_name) > 200 then
    raise exception 'invalid name' using errcode = '22023';
  end if;

  v_name := public.normalize_display_name(p_name);
  if char_length(v_name) not between 1 and 30 then
    raise exception 'invalid name' using errcode = '22023';
  end if;

  if not public.is_name_allowed(v_name) then
    raise exception 'name not allowed' using errcode = '22023';
  end if;

  update public.profiles
  set display_name = v_name
  where id = v_user_id;

  if not found then
    raise exception 'profile missing' using errcode = 'P0002';
  end if;

  return jsonb_build_object('displayName', v_name);
end;
$$;
